name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.ref }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Compile
        run: npm run build
      - name: Build Binaries
        run: npm run dist-server
      - name: Upload Server Binaries
        uses: actions/upload-artifact@v4
        with:
          name: server_${{ github.ref_name }}
          path: dist/server/detocs-server-*
      # - name: Upload App Binaries
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: full_${{ github.ref_name }}
      #     path: dist/full/detocs-*.zip
  draft_release:
    runs-on: ubuntu-latest
    needs: [build_binaries]
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: List Directory Files
        run: ls -la
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: DETOCS ${{ github.ref_name }}
          draft: true
          files: |
            detocs*
